### ISSUE TITLE
AttributeError: 'module' object has no attribute 'BLACK'

### ISSUE THREAD

**Issue by Gasman2014** [mmccoo/kicad_mmccoo#2]
Hi
I am keen to try out python in Kicad and have had some success with some other scripts and some of your  tutorial scripts. This one falls over on me though. Not sure if this is an OS X thing - I have another script which is failing in a very similar way.
```
Py 0.9.8
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Startup script executed: /Users/johnpateman/Library/Preferences/kicad/PyShell_pcbnew_startup.py
execfile("/Users/johnpateman/Library/Preferences/kicad/gensvg.py")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/johnpateman/Library/Preferences/kicad/gensvg.py", line 31, in <module>
    pcbnew.BLACK:         'BLACK',
AttributeError: 'module' object has no attribute 'BLACK'
```

Nightly build Kicad 4.0.6/macOS

Any clues/tricks/suggestions ?

**Comment by mmccoo** [comment]
Thank you for the issue report. Real code has bugs. No bug reports means no users. This is one of the ways I know I should bother.

The problem is that kicad has changed the way colors are managed (for the better). Instead of color names, rgb values are the way to go.

I have updated gensvg on github as well as [my blog entry about this file](https://kicad.mmccoo.com/2017/02/01/querying-pcbnew-to-generate-a-basic-svg-file/)
