### ISSUE TITLE
Fixed filename dialog on svg2border and added svg2Outline item.

### ISSUE THREAD

**Issue by TomWS1** [mmccoo/kicad_mmccoo#8]
The last update to svg2border added file and layer dialogs, which are great additions, however, the filename was never used in the two actions (still referenced the old hardcoded svg file).
While I was updating, I decided that edge.cuts layer really needs an outline, not a filled polygon, so added the svg2outline action to the other two.  The diff file is added below.
[svg2border.txt](https://github.com/mmccoo/kicad_mmccoo/files/2320997/svg2border.txt)

**Comment by mmccoo** [comment]
thank you! I have fixed both issues
- I pass along the filenames
- I generate segments instead of polygons. The existing pcbnew commands don't let you generate polys, so likely problems ensue downstream. So my svg2graphic just creates segements (as proposed in your patch)

Also, svg parsing results with some duplicate endpoints. I haven't taken the time to find out why. So the plugin will just skip zero length segments.


Thank you for taking the time to report. Zero bugs reported means no ones using it which means why should I bother. I can take me months to reply to filed issues, but I try to get to them eventually.

Miles
